server:
  port: 8080

spring:
  application:
    name: api-gateway
  # Descubrimiento autom√°tico de microservicios
  cloud:
    gateway:
      mvc:
        routes:
          - id: publication-service
            uri: lb://publication-service
            predicates:
              - Path=/publication-service/**
            filters:
              - StripPrefix=1
          - id: user-profile-service
            uri: lb://user-profile-service
            predicates:
              - Path=/user-profile-service/**
            filters:
              - StripPrefix=1
          - id: book-service
            uri: lb://book-service
            predicates:
              - Path=/book-service/**
            filters:
              - StripPrefix=1

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true