server:
  port: 8080

spring:
  application:
    name: api-gateway
  # Descubrimiento autom√°tico de microservicios
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: security-service
              uri: lb://security-service
              predicates:
                - Path=/auth/**

            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/books/**, /authors/**, /ratings/**

            - id: publication-service
              uri: lb://publication-service
              predicates:
                - Path=/publications/**, /categories/**, /favorites/**

            - id: user-profile-service
              uri: lb://user-profile-service
              predicates:
                - Path=/user-profiles/**, /announcements/**

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# OpenAPI / Swagger
springdoc:
  swagger-ui:
    urls:
      - name: security-service
        url: http://localhost:8088/openapi.yaml
      - name: user-profile-service
        url: http://localhost:8081/openapi.yaml
      - name: publication-service
        url: http://localhost:8082/openapi.yaml
      - name: book-service
        url: http://localhost:8083/openapi.yaml
    path: /swagger

# JWT (token secret key)
jwt:
  secret: ${SECURITY_KEY}
  expiration: 600000  # 10 minutos en milisegundos