server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: security-service
              uri: lb://security-service
              predicates:
                - Path=/auth/**

            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/books/**, /authors/**, /ratings/**

            - id: publication-service
              uri: lb://publication-service
              predicates:
                - Path=/publications/**, /categories/**, /favorites/**

            - id: user-profile-service
              uri: lb://user-profile-service
              predicates:
                - Path=/user-profiles/**, /announcements/**

            # Rutas gen√©ricas para archivos OpenAPI
            - id: security-openapi
              uri: lb://security-service
              predicates:
                - Path=/security-openapi/**
              filters:
                - SetPath=/openapi.yaml

            - id: user-profile-openapi
              uri: lb://user-profile-service
              predicates:
                - Path=/user-profile-openapi/**
              filters:
                - SetPath=/openapi.yaml

            - id: publication-openapi
              uri: lb://publication-service
              predicates:
                - Path=/publication-openapi/**
              filters:
                - SetPath=/openapi.yaml

            - id: book-openapi
              uri: lb://book-service
              predicates:
                - Path=/book-openapi/**
              filters:
                - SetPath=/openapi.yaml

# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# OpenAPI / Swagger
springdoc:
  swagger-ui:
    urls:
      - name: security-service
        url: /security-openapi/openapi.yaml
      - name: user-profile-service
        url: /user-profile-openapi/openapi.yaml
      - name: publication-service
        url: /publication-openapi/openapi.yaml
      - name: book-service
        url: /book-openapi/openapi.yaml
    path: /swagger

# JWT (token secret key)
jwt:
  secret: ${SECURITY_KEY}